version: '3.1'
services:
  app:
    container_name: product-app
    image: product-app
    build: ./
    ports:
      - "8082:8082"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=product